version: '3'

services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: timer-vue-frontend
    
    # Port for Outside World : Actual Port of service in container! Leaving this note for when I refer to this in the future I won't make the 
    # same mistake I make every time I write a docker compose file!!!!
    ports:
    - '8080:80'
    volumes:
    - '.:/app'
    

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    # /docker-entrypoint-initdb.d/*.js for mongo data init


  timer-go-api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: timer-go-api
    environment:
      - MONGO_SERVER=db
      - MONGO_PORT=27017
      - MONGO_USER=${MONGO_USER}
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - mongodb

volumes:
  dbdata6:

  